spring.application.name=security
server.port=8181

# Config Virtual Threads
spring.threads.virtual.enabled=true

# PostgreSQL
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.flyway.enabled=true

# Observalidade
management.metrics.tags.application: securityapplication
management.endpoints.web.exposure.include: health,info,prometheus
endpoint.prometheus.enabled: true